user_name = input("имя пользователя")
print("имя пользователя:", user_name)
title = input("заголовок заметки")
print("заголовок заметки", title)
content = input("описание заметки")
print("описание заметки", content)
status = input("статус заметки")
print("статус заметки:", status)
temp_created_date = input("день-месяц-год")
print("день-месяц-год:", temp_created_date)
temp_issue_date = input("день-месяц-год")
print("день-месяц-год:", temp_issue_date)
is_active = True